# theme settings
remote_theme: daviddarnes/alembic@main

# site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Rolosoft Limited, rolosoft.com"
description: "Rolosoft software company pioneering added value data through email validation"
url: https://rolosoft.com
logo: /assets/images/logo.png
email: "hello@rolosoft.com"

# ite favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  250: '/assets/images/rolosoft-250x250.png'
  25: '/assets/images/rolosoft-25x25.png'


# Outputting
#permalink: /:categories/:title/

# Jekyll settings
sass:
  style: compressed # Style compression
# permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
# excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# Site navigation
navigation_header:
- title: Home
  url: /index.md
- title: Privacy policy
  url: /privacy-policy.md
- title: Cookie Policy
  url: /cookie-policy.md
- title: Website terms of use
  url: /website-tou.md

navigation_footer:
- title: 
  url: https://darn.es
