# theme settings

#theme: "lone-wolf-theme"
#remote_theme : "manid2/lone-wolf-theme"
#bootswatch_theme: "spacelab" 
remote_theme: daviddarnes/alembic@main

# site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Rolosoft Limited, rolosoft.com"
description: "Rolosoft software company pioneering added value data through email validation"
url: https://rolosoft.com
logo: assets/images/logo.png
email: "hello@rolosoft.com"

# Outputting
permalink: /:categories/:title/

# Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"
