# theme settings

#theme: "lone-wolf-theme"
#remote_theme : "manid2/lone-wolf-theme"
#bootswatch_theme: "spacelab" 
remote_theme: "mmistakes/jekyll-theme-basically-basic"

# site settings
title: "Rolosoft software services"
description: "Rolosoft software company pioneering added value data through email validation"
url: https://rolosoft.com
logo: assets/images/logo.png

# Outputting
permalink: /:categories/:title/
